### ISSUE TITLE
Support for specifying versions

### ISSUE THREAD

**Issue by pnewb** [asmallteapot/cocoapods-playgrounds#24]
This came up while attempting to install Siesta, which has no stable release, but does have a functional '1.0-beta.6' tag.  Installable and functional via a Podfile entry like:

'Siesta', '>= 1.0-beta.6'

But the comma throws a wrench in the works.  It attempts to pick up the version specification as another framework.

As a side note, when attempting things like:

pod playgrounds --verbose 'Siesta, ~> 1.0-beta.6'

Relatedly I appear to have managed to get passed through (perhaps by way of workspace.rb's @cwd = Pathname.getpwd) a `rm -fr ~`.  I can't say if it was that precise version of the commands I tried, but there were many.  Suddenly (and embarrassingly) I was missing a large number of files in my home directory.  I hesitate to submit this precise thing as a bug in part because I've yet to replicate it...and that's because I've yet to _attempt_ to replicate it.  Hopefully you can understand why I might be hesitant to do so.

**Comment by neonichu** [comment]
Oh, that's bad 😞 Hope you had backups of those files. That's a really bad bug even if it is hard to trigger. I'll try to look a bit more into how that could happen, potentially because arguments are also tried out as a path (see #23) and your version specification turned into a valid path.

As for specifying versions, I don't think I want to support it in the CLI arguments at this point, because this will be hard to make non-confusing with the existing feature of passing a list of Pods. I think just generating with Siesta and manually changing the Podfile later should work?

**Comment by neonichu** [comment]
OK, I see now how the deletion can happen, e.g. if you pass `pod playgrounds 'bar,~ foo'` it'll end up calling `rm -rf ~ foo`. I'm going to quote that argument to fix this.

**Comment by neonichu** [comment]
Again, I'm really sorry for this bug, I didn't anticipate people trying to pass versions or the pessimistic operator here.

Regarding the specification of versions, I would recommend using the new `--no-install` option to just generate the Playground and manually add the version to the generated Podfile.

**Comment by pnewb** [comment]
I did indeed have backups.  My coworkers got a laugh, nothing of value was lost.  Thank you for the quick fix!  I did figure out that I could just add Siesta after the fact, like you suggested.

As someone who's just now trying to do _anything_ in Xcode for the first time ever, thank you for the tool.  I struggled longer than I'd like to admit with trying to do this by hand.

**Comment by neonichu** [comment]
Glad that it is helpful :)
